[2024-10-27T23:06:18.928+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-27T23:06:18.944+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_webscraping.pichau_tasks.Web_Extraction_pichau manual__2024-10-27T23:06:14.557917+00:00 [queued]>
[2024-10-27T23:06:18.952+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_webscraping.pichau_tasks.Web_Extraction_pichau manual__2024-10-27T23:06:14.557917+00:00 [queued]>
[2024-10-27T23:06:18.952+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-27T23:06:18.970+0000] {taskinstance.py:2888} INFO - Executing <Task(OperatorSiteA): pichau_tasks.Web_Extraction_pichau> on 2024-10-27 23:06:14.557917+00:00
[2024-10-27T23:06:18.978+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-27T23:06:18.982+0000] {standard_task_runner.py:72} INFO - Started process 1132 to run task
[2024-10-27T23:06:18.980+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_webscraping', 'pichau_tasks.Web_Extraction_pichau', 'manual__2024-10-27T23:06:14.557917+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/DagWebScraping.py', '--cfg-path', '/tmp/tmpwm622gn6']
[2024-10-27T23:06:18.983+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask pichau_tasks.Web_Extraction_pichau
[2024-10-27T23:06:19.056+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_webscraping.pichau_tasks.Web_Extraction_pichau manual__2024-10-27T23:06:14.557917+00:00 [running]> on host 3324bb551f35
[2024-10-27T23:06:19.133+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline_webscraping' AIRFLOW_CTX_TASK_ID='pichau_tasks.Web_Extraction_pichau' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T23:06:14.557917+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T23:06:14.557917+00:00'
[2024-10-27T23:06:19.136+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-27T23:06:33.991+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteA.py", line 97, in execute
    self._ProcessamentoBeautifulSoup()
  File "/opt/airflow/operators/OperatorSiteA.py", line 64, in _ProcessamentoBeautifulSoup
    WebDriverWait(driver, 10).until(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x56103158c10a <unknown>
#1 0x5610310a7460 <unknown>
#2 0x5610310f3f96 <unknown>
#3 0x5610310f4221 <unknown>
#4 0x5610311395d4 <unknown>
#5 0x56103111803d <unknown>
#6 0x561031136af6 <unknown>
#7 0x561031117db3 <unknown>
#8 0x5610310e6c10 <unknown>
#9 0x5610310e7bee <unknown>
#10 0x56103155839b <unknown>
#11 0x56103155c338 <unknown>
#12 0x561031545ebc <unknown>
#13 0x56103155ceb7 <unknown>
#14 0x56103152b10f <unknown>
#15 0x56103157a828 <unknown>
#16 0x56103157a9f0 <unknown>
#17 0x56103158af86 <unknown>
#18 0x7fa7f776ba94 <unknown>
#19 0x7fa7f77f8c3c <unknown>

[2024-10-27T23:06:34.010+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=pipeline_webscraping, task_id=pichau_tasks.Web_Extraction_pichau, run_id=manual__2024-10-27T23:06:14.557917+00:00, execution_date=20241027T230614, start_date=20241027T230618, end_date=20241027T230634
[2024-10-27T23:06:34.026+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-27T23:06:34.027+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task pichau_tasks.Web_Extraction_pichau (Message: 
Stacktrace:
#0 0x56103158c10a <unknown>
#1 0x5610310a7460 <unknown>
#2 0x5610310f3f96 <unknown>
#3 0x5610310f4221 <unknown>
#4 0x5610311395d4 <unknown>
#5 0x56103111803d <unknown>
#6 0x561031136af6 <unknown>
#7 0x561031117db3 <unknown>
#8 0x5610310e6c10 <unknown>
#9 0x5610310e7bee <unknown>
#10 0x56103155839b <unknown>
#11 0x56103155c338 <unknown>
#12 0x561031545ebc <unknown>
#13 0x56103155ceb7 <unknown>
#14 0x56103152b10f <unknown>
#15 0x56103157a828 <unknown>
#16 0x56103157a9f0 <unknown>
#17 0x56103158af86 <unknown>
#18 0x7fa7f776ba94 <unknown>
#19 0x7fa7f77f8c3c <unknown>
; 1132)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteA.py", line 97, in execute
    self._ProcessamentoBeautifulSoup()
  File "/opt/airflow/operators/OperatorSiteA.py", line 64, in _ProcessamentoBeautifulSoup
    WebDriverWait(driver, 10).until(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x56103158c10a <unknown>
#1 0x5610310a7460 <unknown>
#2 0x5610310f3f96 <unknown>
#3 0x5610310f4221 <unknown>
#4 0x5610311395d4 <unknown>
#5 0x56103111803d <unknown>
#6 0x561031136af6 <unknown>
#7 0x561031117db3 <unknown>
#8 0x5610310e6c10 <unknown>
#9 0x5610310e7bee <unknown>
#10 0x56103155839b <unknown>
#11 0x56103155c338 <unknown>
#12 0x561031545ebc <unknown>
#13 0x56103155ceb7 <unknown>
#14 0x56103152b10f <unknown>
#15 0x56103157a828 <unknown>
#16 0x56103157a9f0 <unknown>
#17 0x56103158af86 <unknown>
#18 0x7fa7f776ba94 <unknown>
#19 0x7fa7f77f8c3c <unknown>

[2024-10-27T23:06:34.052+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-27T23:06:34.075+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-27T23:06:34.081+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
