[2024-09-28T18:48:17.597+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-28T18:48:17.616+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SitesWebScraping.WebScrapint manual__2024-09-28T18:48:15.382681+00:00 [queued]>
[2024-09-28T18:48:17.629+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SitesWebScraping.WebScrapint manual__2024-09-28T18:48:15.382681+00:00 [queued]>
[2024-09-28T18:48:17.631+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-28T18:48:17.651+0000] {taskinstance.py:2888} INFO - Executing <Task(WebScraping_K): WebScrapint> on 2024-09-28 18:48:15.382681+00:00
[2024-09-28T18:48:17.658+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-28T18:48:17.662+0000] {standard_task_runner.py:72} INFO - Started process 4146 to run task
[2024-09-28T18:48:17.661+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'SitesWebScraping', 'WebScrapint', 'manual__2024-09-28T18:48:15.382681+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/DagWebScraping.py', '--cfg-path', '/tmp/tmpf9xmv9vn']
[2024-09-28T18:48:17.664+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask WebScrapint
[2024-09-28T18:48:17.811+0000] {task_command.py:467} INFO - Running <TaskInstance: SitesWebScraping.WebScrapint manual__2024-09-28T18:48:15.382681+00:00 [running]> on host 195e9906c829
[2024-09-28T18:48:17.902+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SitesWebScraping' AIRFLOW_CTX_TASK_ID='WebScrapint' AIRFLOW_CTX_EXECUTION_DATE='2024-09-28T18:48:15.382681+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-28T18:48:15.382681+00:00'
[2024-09-28T18:48:17.905+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-28T18:48:24.655+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorWebScraping.py", line 129, in execute
    self.ExtractDates()
  File "/opt/airflow/operators/OperatorWebScraping.py", line 95, in ExtractDates
    self.__ProcessamentoBeautifulSoup(html, url)
  File "/opt/airflow/operators/OperatorWebScraping.py", line 70, in __ProcessamentoBeautifulSoup
    'value':value,
            ^^^^^
UnboundLocalError: cannot access local variable 'value' where it is not associated with a value
[2024-09-28T18:48:24.668+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=SitesWebScraping, task_id=WebScrapint, run_id=manual__2024-09-28T18:48:15.382681+00:00, execution_date=20240928T184815, start_date=20240928T184817, end_date=20240928T184824
[2024-09-28T18:48:24.685+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-28T18:48:24.686+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 249 for task WebScrapint (cannot access local variable 'value' where it is not associated with a value; 4146)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorWebScraping.py", line 129, in execute
    self.ExtractDates()
  File "/opt/airflow/operators/OperatorWebScraping.py", line 95, in ExtractDates
    self.__ProcessamentoBeautifulSoup(html, url)
  File "/opt/airflow/operators/OperatorWebScraping.py", line 70, in __ProcessamentoBeautifulSoup
    'value':value,
            ^^^^^
UnboundLocalError: cannot access local variable 'value' where it is not associated with a value
[2024-09-28T18:48:24.721+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-28T18:48:24.742+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T18:48:24.745+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
