[2024-08-21T19:33:34.579+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta manual__2024-08-21T19:33:32.085372+00:00 [queued]>
[2024-08-21T19:33:34.587+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta manual__2024-08-21T19:33:32.085372+00:00 [queued]>
[2024-08-21T19:33:34.588+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-08-21T19:33:34.605+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-08-21 19:33:32.085372+00:00
[2024-08-21T19:33:34.610+0000] {standard_task_runner.py:60} INFO - Started process 69 to run task
[2024-08-21T19:33:34.613+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'manual__2024-08-21T19:33:32.085372+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpue97mvrl']
[2024-08-21T19:33:34.614+0000] {standard_task_runner.py:88} INFO - Job 112: Subtask cria_pasta
[2024-08-21T19:33:34.660+0000] {task_command.py:423} INFO - Running <TaskInstance: dados_climaticos.cria_pasta manual__2024-08-21T19:33:32.085372+00:00 [running]> on host aaa07c95d172
[2024-08-21T19:33:34.732+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos' AIRFLOW_CTX_TASK_ID='cria_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T19:33:32.085372+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T19:33:32.085372+00:00'
[2024-08-21T19:33:34.735+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T19:33:34.736+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p /usr/local/***/custom_pasta/semana=2024-08-19"']
[2024-08-21T19:33:34.747+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T19:33:34.748+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2024-08-21T19:33:34.749+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-21T19:33:34.758+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-21T19:33:34.764+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240821T193332, start_date=20240821T193334, end_date=20240821T193334
[2024-08-21T19:33:34.780+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 112 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 2.; 69)
[2024-08-21T19:33:34.825+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-21T19:33:34.850+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
