[2024-10-05T14:06:45.560+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-05T14:06:45.576+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pichau_pipeline.pichau_tasks.Web_Extraction_pichau manual__2024-10-05T14:06:41.944913+00:00 [queued]>
[2024-10-05T14:06:45.583+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pichau_pipeline.pichau_tasks.Web_Extraction_pichau manual__2024-10-05T14:06:41.944913+00:00 [queued]>
[2024-10-05T14:06:45.584+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-05T14:06:45.600+0000] {taskinstance.py:2888} INFO - Executing <Task(OperatorSiteA): pichau_tasks.Web_Extraction_pichau> on 2024-10-05 14:06:41.944913+00:00
[2024-10-05T14:06:45.604+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3436) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-05T14:06:45.606+0000] {standard_task_runner.py:72} INFO - Started process 3444 to run task
[2024-10-05T14:06:45.606+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pichau_pipeline', 'pichau_tasks.Web_Extraction_pichau', 'manual__2024-10-05T14:06:41.944913+00:00', '--job-id', '1173', '--raw', '--subdir', 'DAGS_FOLDER/DagWebScraping.py', '--cfg-path', '/tmp/tmp2k18262e']
[2024-10-05T14:06:45.608+0000] {standard_task_runner.py:105} INFO - Job 1173: Subtask pichau_tasks.Web_Extraction_pichau
[2024-10-05T14:06:45.652+0000] {task_command.py:467} INFO - Running <TaskInstance: pichau_pipeline.pichau_tasks.Web_Extraction_pichau manual__2024-10-05T14:06:41.944913+00:00 [running]> on host e823e678f418
[2024-10-05T14:06:45.731+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pichau_pipeline' AIRFLOW_CTX_TASK_ID='pichau_tasks.Web_Extraction_pichau' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T14:06:41.944913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-05T14:06:41.944913+00:00'
[2024-10-05T14:06:45.732+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-05T14:09:06.243+0000] {logging_mixin.py:190} INFO - Create_Container_Raw_pichau
[2024-10-05T14:09:06.276+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteA.py", line 98, in execute
    self.SaveFile(context)
  File "/opt/airflow/operators/OperatorSiteBase.py", line 84, in SaveFile
    with open(filepath, 'w', encoding='utf-8') as arquivo:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/datalake/rawzone/pichau_2024-10-05/data.json'
[2024-10-05T14:09:06.290+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=pichau_pipeline, task_id=pichau_tasks.Web_Extraction_pichau, run_id=manual__2024-10-05T14:06:41.944913+00:00, execution_date=20241005T140641, start_date=20241005T140645, end_date=20241005T140906
[2024-10-05T14:09:06.306+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-05T14:09:06.307+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1173 for task pichau_tasks.Web_Extraction_pichau ([Errno 2] No such file or directory: '/opt/airflow/datalake/rawzone/pichau_2024-10-05/data.json'; 3444)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteA.py", line 98, in execute
    self.SaveFile(context)
  File "/opt/airflow/operators/OperatorSiteBase.py", line 84, in SaveFile
    with open(filepath, 'w', encoding='utf-8') as arquivo:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/datalake/rawzone/pichau_2024-10-05/data.json'
[2024-10-05T14:09:06.343+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-05T14:09:06.370+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-05T14:09:06.375+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
