[2024-11-04T11:02:40.659+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:02:40.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:02:40.665+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:02:40.664+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:02:40.724+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:02:40.717+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:02:40.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:02:40.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.136 seconds
[2024-11-04T11:03:11.227+0000] {processor.py:186} INFO - Started process (PID=90) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:03:11.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:03:11.231+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:03:11.230+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:03:11.244+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:03:11.243+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:03:11.245+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:03:11.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.045 seconds
[2024-11-04T11:03:41.621+0000] {processor.py:186} INFO - Started process (PID=115) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:03:41.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:03:41.624+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:03:41.623+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:03:41.639+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:03:41.637+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:03:41.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:03:41.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.043 seconds
[2024-11-04T11:04:12.530+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:04:12.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:04:12.535+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:04:12.535+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:04:12.553+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:04:12.552+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:04:12.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:04:12.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.054 seconds
[2024-11-04T11:04:43.112+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:04:43.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:04:43.121+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:04:43.121+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:04:43.143+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:04:43.138+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:04:43.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:04:43.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.076 seconds
[2024-11-04T11:05:13.609+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:05:13.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:05:13.622+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:05:13.621+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:05:13.640+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:05:13.639+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:05:13.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:05:13.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.063 seconds
[2024-11-04T11:05:43.949+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:05:43.951+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:05:43.954+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:05:43.954+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:05:43.974+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:05:43.973+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:05:43.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:05:44.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.067 seconds
[2024-11-04T11:06:14.292+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:06:14.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:06:14.295+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:06:14.294+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:06:14.309+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:06:14.308+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:06:14.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:06:14.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.051 seconds
[2024-11-04T11:06:44.720+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:06:44.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:06:44.723+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:06:44.723+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:06:44.738+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:06:44.737+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:06:44.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:06:44.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.043 seconds
[2024-11-04T11:07:15.051+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:07:15.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:07:15.058+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:07:15.057+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:07:15.079+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:07:15.078+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:07:15.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:07:15.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.100 seconds
[2024-11-04T11:07:45.557+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:07:45.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:07:45.561+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:07:45.561+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:07:45.576+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:07:45.575+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:07:45.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:07:45.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.049 seconds
[2024-11-04T11:08:15.761+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:08:15.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:08:15.766+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:08:15.765+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:08:15.783+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:08:15.782+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:08:15.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:08:15.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.066 seconds
[2024-11-04T11:08:46.321+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:08:46.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:08:46.327+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:08:46.327+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:08:46.343+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:08:46.342+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:08:46.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:08:46.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.074 seconds
[2024-11-04T11:09:16.995+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:09:16.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:09:17.000+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:09:16.999+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:09:17.018+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:09:17.017+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:09:17.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:09:17.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.065 seconds
[2024-11-04T11:09:47.458+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:09:47.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:09:47.462+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:09:47.462+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:09:47.478+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:09:47.477+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:09:47.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:09:47.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.052 seconds
[2024-11-04T11:10:18.121+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:10:18.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:10:18.126+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:10:18.126+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:10:18.146+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:10:18.144+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:10:18.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:10:18.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.052 seconds
[2024-11-04T11:10:48.653+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:10:48.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:10:48.657+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:10:48.657+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:10:48.705+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:10:48.702+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:10:48.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:10:48.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.093 seconds
[2024-11-04T11:11:18.941+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:11:18.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:11:18.945+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:11:18.944+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:11:18.979+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:11:18.978+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:11:18.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:11:19.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.084 seconds
[2024-11-04T11:11:49.676+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:11:49.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:11:49.682+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:11:49.682+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:11:49.736+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:11:49.735+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:11:49.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:11:49.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.103 seconds
[2024-11-04T11:12:19.959+0000] {processor.py:186} INFO - Started process (PID=543) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:12:19.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:12:19.963+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:12:19.963+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:12:19.981+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:12:19.980+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:12:19.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:12:20.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.106 seconds
[2024-11-04T11:12:50.868+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:12:50.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:12:50.872+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:12:50.871+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:12:50.886+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:12:50.885+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:12:50.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:12:50.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.045 seconds
[2024-11-04T11:13:21.541+0000] {processor.py:186} INFO - Started process (PID=594) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:13:21.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:13:21.545+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:13:21.544+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:13:21.559+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:13:21.558+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:13:21.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:13:21.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.046 seconds
[2024-11-04T11:13:52.638+0000] {processor.py:186} INFO - Started process (PID=619) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:13:52.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:13:52.641+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:13:52.641+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:13:52.656+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:13:52.656+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:13:52.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:13:52.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.046 seconds
[2024-11-04T11:14:23.640+0000] {processor.py:186} INFO - Started process (PID=644) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:14:23.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:14:23.645+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:14:23.645+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:14:23.659+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:14:23.658+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:14:23.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:14:23.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.045 seconds
[2024-11-04T11:14:54.520+0000] {processor.py:186} INFO - Started process (PID=669) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:14:54.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:14:54.524+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:14:54.524+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:14:54.540+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:14:54.539+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:14:54.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:14:54.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.046 seconds
[2024-11-04T11:15:25.316+0000] {processor.py:186} INFO - Started process (PID=694) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:15:25.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:15:25.319+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:15:25.319+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:15:25.334+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:15:25.333+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:15:25.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:15:25.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.047 seconds
[2024-11-04T11:15:55.728+0000] {processor.py:186} INFO - Started process (PID=720) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:15:55.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:15:55.732+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:15:55.732+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:15:55.747+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:15:55.746+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:15:55.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:15:55.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.046 seconds
[2024-11-04T11:16:26.714+0000] {processor.py:186} INFO - Started process (PID=745) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:16:26.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:16:26.718+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:16:26.717+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:16:26.734+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:16:26.733+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:16:26.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:16:26.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.049 seconds
[2024-11-04T11:16:57.598+0000] {processor.py:186} INFO - Started process (PID=770) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:16:57.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:16:57.602+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:16:57.602+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:16:57.619+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:16:57.618+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:16:57.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:16:57.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.053 seconds
[2024-11-04T11:17:27.866+0000] {processor.py:186} INFO - Started process (PID=795) to work on /opt/airflow/dags/windturbine.py
[2024-11-04T11:17:27.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/windturbine.py for tasks to queue
[2024-11-04T11:17:27.874+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:17:27.873+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/windturbine.py
[2024-11-04T11:17:27.889+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:17:27.888+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/windturbine.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/windturbine.py", line 68
    '{{ti.xcom_pull(task_ids=get_data),key=timestamp}}'
    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-11-04T11:17:27.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/windturbine.py
[2024-11-04T11:17:27.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/windturbine.py took 0.051 seconds
